# ansible playbook to set up some docker containers

- name: Set up an analytics node
  hosts: dev
  gather_facts: true
  tasks:
    - name: Create network
      community.docker.docker_network:
        name: analytics-net
        state: present
        driver: bridge

    - name: Create postgres containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: postgres:16
        state: started
        restart_policy: unless-stopped
        network_mode: analytics-net
        env:
          POSTGRES_USER: analytics
          POSTGRES_PASSWORD: securepass
          POSTGRES_DB: analytics_db
        volumes:
          - "{{ item.name }}_data:/var/lib/postgresql/data"
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "analytics"]
          interval: 5s
          timeout: 3s
          retries: 5
      loop:
        - name: analytics-postgres
        - name: analytics-postgres-metrics

    - name: Set up mailcatcher
      community.docker.docker_container:
        name: analytics-mail
        image: schickling/mailcatcher
        state: started
        restart_policy: unless-stopped
        network_mode: analytics-net

    - name: Run the analytics API backend
      community.docker.docker_container:
        name: analytics-backend
        image: myregistry.io/analytics/api-backend:latest
        state: started
        pull: true
        restart_policy: unless-stopped
        network_mode: analytics-net
        env:
          POSTGRES_HOST: analytics-postgres
          API_KEY_ALLOW_ALL: "true"
          WORKER_THREADS: "4"
        ports:
          - 5000:5000

    - name: Run the analytics dashboard frontend
      community.docker.docker_container:
        name: analytics-dashboard
        image: myregistry.io/analytics/frontend:latest
        state: started
        pull: true
        restart_policy: unless-stopped
        network_mode: analytics-net
        env:
          API_URL: http://analytics-backend:5000
          API_KEY: "supersecret"
          DATABASE_URL: postgres://analytics:securepass@analytics-postgres-metrics/analytics_db
          AUTH_SECRET: s3cur3S3cr3tK3y!
          MAIL_SERVER: analytics-mail
          MAIL_PORT: "1025"
          MAIL_FROM: no-reply@analytics.io
          DASHBOARD_URL: http://dashboard.analytics.dev/
        ports:
          - 4000:3000
        command: bash wait-for-db.sh && node start-dashboard.js
